### ISSUE TITLE
File name encoding error in BDD

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/photoview_ynh#10]
### Describe the bug

Some files can not be scanned, due to an encoding problem.
For example : 
```
Scanner error

Error scanning media for album (10656): Scanning media error (/path/to/nextcloud/data/mamie/files/Backup/Gray Wagtail and Lotus 灰鶺鴒和蓮花.png): could not insert media into database: Error 1366: Incorrect string value: '\xE7\x81\xB0\xE9\xB6\xBA...' for column `photoview`.`media`.`title` at row 1 
```

It also happens for more "simple" chars, as `è`

### Context

- Hardware: *computer*
- YunoHost version: 4.2.6.1
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *master*

### Steps to reproduce
Add a file with special chars in a folder managed by photoview.
Wait for tho scan to happen.
See the error.

### Expected behavior

All files should be available

**Comment by Jules-Bertholet** [comment]
This looks like an upstream bug, report to https://github.com/photoview/photoview/issues
