### ISSUE TITLE
Passer sur la version 2.3.12

### ISSUE THREAD

**Issue by mastogros** [YunoHost-Apps/photoview_ynh#21]
Bonjour, serait-il possible de passer sur la dernière version ? (2.3.12)

Merci !

**Comment by mastogros** [comment]
Merci bcp!
Upgrade nickel, juste faite en ligne de commande avec le -b pour ne pas faire de backup car avec une grosse bibliothèque d'images ça ferait planter le serveur. Ça serait pas mal de pouvoir spécifier pas de backup dans l'interface d'admin.

**Comment by Jules-Bertholet** [comment]
@mastogros Le backup ne devrait pas inclure ta bibliothèque d'images en entier, seulement les vignettes.

**Comment by mastogros** [comment]
@Jules-Bertholet Yes, mais dans mon cas même juste les vignettes, ça représente quand même 50Go donc je préfère pas, dans le cas de ce passage de version les backups ça serait trop long pour un risque inexistant puisque sur un disque monté. D'ailleurs ça serait pas mal d'avoir la possibilité de régler ce qu'on veut backup ou non, car par contre le mysql c'est interessant de le faire au cas où.
En tout cas merci encore pour avoir fait la maj !
