### ISSUE TITLE
Documentation cannot be found

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/photoview_ynh#26]
Link in Readme to Yunohost Photoview documentation is not working. 
Searching yunohost.org for documentation gives no results, so no idea if the link is fixable. 

![220612-090336](https://user-images.githubusercontent.com/651760/173219287-a348abdb-7001-4e29-a1a1-98e7952c6898.png)

**Comment by yalh76** [comment]
It will be fixed the day someone will create it in Yunohost documentation
