### ISSUE TITLE
Install proccess wont go any further...

### ISSUE THREAD

**Issue by penguin321** [YunoHost-Apps/photoview_ynh#7]
![grafik](https://user-images.githubusercontent.com/67345594/120082530-d931b000-c0c3-11eb-8d08-7acdf53f693f.png)

I wanted to install photoview on the newest Yunohost edition, but everytime in the install process its kinda stuck at the "installing go" line. Then i tried the debug run and obove is the screenshot where it shows the stuck point.

**Comment by Jules-Bertholet** [comment]
It's normal for this step to take a while, especially on low-powered hardware. I don't know whether you have that, because you didn't fill out the issue template (so I will be closing this).
